import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [walletAddress, setWalletAddress] = useState("");
  const [collectionAddress, setCollectionAddress] = useState("");
  const [nfts, setNfts] = useState([]);

  const fetchNft = async (e) => {
    let nfts;
    console.log("Fetching Nfts");

    const apiKey = "Your Mainnet Apki Key";
    const baseURL = `https://eth-mainnet.g.alchemy.com/nft/v2/${apiKey}/getNFTs/`;

    if (!collectionAddress.length) {
      var requestOptions = {
        method: "GET",
        redirect: "follow",
      };

      const fetchURL = `${baseURL}?owner=${walletAddress}`;

      nfts = await fetch(fetchURL, requestOptions).then((data) => data.json());
    } else {
      const fetchURL = `${baseURL}?owner=${walletAddress}&contractAddresses%5B%5D=${collectionAddress}`;
      nfts = await fetch(fetchURL, requestOptions).then((data) => data.json());
    }

    if (nfts) {
      console.log(nfts);
      setNfts(nfts);
    }
  };

  return (
    <>
      <Head>
        <title>NFT Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" m-8 ">
        <div className="flex flex-col space-y-4 mx-auto max-w-md">
          <input
            type="text"
            value={walletAddress}
            onChange={(e) => setWalletAddress(e.target.value)}
            placeholder="Add Wallet Address"
            className="border outline-none"
          />
          <input
            type="text"
            value={collectionAddress}
            onChange={(e) => setCollectionAddress(e.target.value)}
            placeholder="Add Collection Address"
            className="border outline-none"
          />
          <label>
            <input type="checkbox" className="" />
          </label>
          <button
            className="border w-[120px] rounded-lg text-gray-600 h-[40px] flex items-center justify-center"
            onClick={() => fetchNft()}
          >
            Let's Go!
          </button>
        </div>
      </div>
    </>
  );
}
